# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeCSMatrix2 <- function(la) {
    .Call(`_LATools_makeCSMatrix2`, la)
}

makeLA2 <- function(file, factorDataFile) {
    .Call(`_LATools_makeLA2`, file, factorDataFile)
}

createModels_wrapper <- function(la_, response_, csMatrix_, maxTerms_, models_n_, newModels_n_, logit_) {
    .Call(`_LATools_createModels_wrapper`, la_, response_, csMatrix_, maxTerms_, models_n_, newModels_n_, logit_)
}

makeVectorXF2 <- function(length, response_dir, response_column, log_data) {
    .Call(`_LATools_makeVectorXF2`, length, response_dir, response_column, log_data)
}

rcpp_hello_world <- function() {
    .Call(`_LATools_rcpp_hello_world`)
}

